export default [
    {
        id:1,
        fname:"krupal",
        lname:"bavishi",
        rank:"A",
        score:100
    },
    {
        id:3,
        fname:"krupal", 
        lname:"bavishi",
        rank:"C",
        score:50
    },
    {
        id:4,
        fname:"margin",
        lname:"nasit",
        rank:"B",
        score:70
    },
    {
        id:2,
        fname:"krupal",
        lname:"patel",
        rank:"B",
        score:75
    },
    {
        id:5,
        fname:"maharshi", 
        lname:"patel",
        rank:"C",
        score:55
    },
    {
        id:6,
        fname:"rajvee", 
        lname:"varotaria",
        rank:"A",
        score:95
    },
    {
        id:7,
        fname:"hetshi",
        lname:"patel",
        rank:"C",
        score:45
    },
    {
        id:9,
        fname:"avadh",
        lname:"koyani",
        rank:"D",
        score:30
    },
    {
        id:8,
        fname:"khushi",
        lname:"shah",
        rank:"E",
        score:10
    }
]